spring:
  application:
    name: FreelanceMarketplace
  datasource:
    url: jdbc:postgresql://localhost:5432/freelance_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# JWT Configuration
jwt:
  secret: "your-base64-encoded-secret" # Generate via: openssl rand -base64 32
  expiration: 86400000 # 24 hours

# Notification email
notification:
  email: "notifications@freelance.marketplace.com"